"""first migrate

Revision ID: 38f0605ff047
Revises:
Create Date: 2021-08-16 11:53:07.162248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f0605ff047'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('address_line_one', sa.String(
                        length=100), nullable=False),
                    sa.Column('address_line_two', sa.String(
                        length=100), nullable=True),
                    sa.Column('city', sa.String(length=50), nullable=False),
                    sa.Column('state', sa.String(length=2), nullable=False),
                    sa.Column('postal_code', sa.Integer(), nullable=False),
                    sa.Column('country', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('businesses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('business_name', sa.String(
                        length=50), nullable=True),
                    sa.Column('first_name', sa.String(
                        length=30), nullable=True),
                    sa.Column('last_name', sa.String(
                        length=50), nullable=True),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('business_name'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('cuisines',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(length=30), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=20), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=30), nullable=False),
                    sa.Column('birth_date', sa.Date(), nullable=False),
                    sa.Column('img_url', sa.Text(), nullable=True),
                    sa.Column('gender', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('business_reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('business_id', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['business_id'], ['businesses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('restaurants',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('restaurant_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('phone_number', sa.String(
                        length=14), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('price_range', sa.Integer(), nullable=False),
                    sa.Column('address_id', sa.Integer(), nullable=False),
                    sa.Column('business_id', sa.Integer(), nullable=False),
                    sa.Column('cuisine_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['address_id'], ['restaurants.id'], ),
                    sa.ForeignKeyConstraint(
                        ['business_id'], ['businesses.id'], ),
                    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisines.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('phone_number')
                    )
    op.create_table('user_reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.String(), nullable=False),
                    sa.Column('photo', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('img_url', sa.Text(), nullable=False),
                    sa.Column('restaurant_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurants.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reservations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('restaurant_id', sa.Integer(), nullable=False),
                    sa.Column('number_of_guests',
                              sa.Integer(), nullable=False),
                    sa.Column('date_start', sa.Date(), nullable=False),
                    sa.Column('time_start', sa.Time(), nullable=False),
                    sa.Column('share_table', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurants.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('restaurant_reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('restaurant_id', sa.Integer(), nullable=True),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.String(), nullable=False),
                    sa.Column('photo', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurants.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rewards',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('restaurant_id', sa.Integer(), nullable=False),
                    sa.Column('reward_amount', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurants.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewards')
    op.drop_table('restaurant_reviews')
    op.drop_table('reservations')
    op.drop_table('images')
    op.drop_table('user_reviews')
    op.drop_table('restaurants')
    op.drop_table('business_reviews')
    op.drop_table('users')
    op.drop_table('cuisines')
    op.drop_table('businesses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
