"""empty message

Revision ID: b4a1a85b81e0
Revises: ed1950200870
Create Date: 2021-09-30 18:05:36.780140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a1a85b81e0'
down_revision = 'ed1950200870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reviews', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_reviews', 'images', ['image_id'], ['id'])
    op.create_foreign_key(None, 'user_reviews', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_reviews', type_='foreignkey')
    op.drop_constraint(None, 'user_reviews', type_='foreignkey')
    op.drop_column('user_reviews', 'restaurant_id')
    # ### end Alembic commands ###
