"""empty message

Revision ID: ed1950200870
Revises: 38f0605ff047
Create Date: 2021-08-20 00:38:53.810274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1950200870'
down_revision = '38f0605ff047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_reviews', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'restaurant_reviews', 'images', ['image_id'], ['id'])
    op.drop_constraint('restaurants_address_id_fkey', 'restaurants', type_='foreignkey')
    op.create_foreign_key(None, 'restaurants', 'addresses', ['address_id'], ['id'])
    op.add_column('user_reviews', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_reviews', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_reviews', type_='foreignkey')
    op.drop_column('user_reviews', 'image_id')
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.create_foreign_key('restaurants_address_id_fkey', 'restaurants', 'restaurants', ['address_id'], ['id'])
    op.drop_constraint(None, 'restaurant_reviews', type_='foreignkey')
    op.drop_column('restaurant_reviews', 'image_id')
    # ### end Alembic commands ###
