sushi = Cuisine(type="Sushi")
bbq = Cuisine(type="BBQ")
italian = Cuisine(type="Italian")
thai = Cuisine(type="Thai")
vegan = Cuisine(type="Vegan")
french = Cuisine(type="French")
vietnamese = Cuisine(type="Vietnamese")
korean = Cuisine(type="Korean")
american = Cuisine(type="American")
southern = Cuisine(type="Southern")
indian = Cuisine(type="Indian")

