# Monte
# 1 { img_url: "https://tabletalkproject.s3.us-west-1.amazonaws.com/Crazy+Rockn+Sushi/Crazy-Rockn-Sushi.jpg", restaurant_id: "1", created_at: new Date(), updated_at: new Date() },
# 1 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/carmelriverinn/64442050.jpeg", restaurant_id: "1", created_at: new Date(), updated_at: new Date() },
# 1 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/carmelriverinn/53916777.jpeg", restaurant_id: "1", created_at: new Date(), updated_at: new Date() },
# 1 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/carmelriverinn/53916701.jpeg", restaurant_id: "1", created_at: new Date(), updated_at: new Date() },
# 2 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/carmelriverinn/64442884.jpeg", restaurant_id: "2", created_at: new Date(), updated_at: new Date() },
# 2 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/carmelriverinn/64442031.jpeg", restaurant_id: "2", created_at: new Date(), updated_at: new Date() },
# 2 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/carmelriverinn/64441989.jpeg", restaurant_id: "2", created_at: new Date(), updated_at: new Date() },
# 2 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/contentainn/nnQQ1uP.jpeg", restaurant_id: "2", created_at: new Date(), updated_at: new Date() },
# 3 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/contentainn/mqQERy8.jpeg", restaurant_id: "3", created_at: new Date(), updated_at: new Date() },
# 3 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/contentainn/KDR8YN4.jpeg", restaurant_id: "3", created_at: new Date(), updated_at: new Date() },
# 3 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/contentainn/ICA5TE0.jpeg", restaurant_id: "3", created_at: new Date(), updated_at: new Date() },
# 3 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/contentainn/iqkK4Jx.jpeg", restaurant_id: "3", created_at: new Date(), updated_at: new Date() },

# Sunny
# 4 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/contentainn/DZlGNxh.jpeg", restaurant_id: "4", created_at: new Date(), updated_at: new Date() },
# 4 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/contentainn/kb1ZOa5.jpeg", restaurant_id: "4", created_at: new Date(), updated_at: new Date() },
# 4 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/blueskylodge/1.jpeg", restaurant_id: "4", created_at: new Date(), updated_at: new Date() },
# 4 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/blueskylodge/2.jpeg", restaurant_id: "4", created_at: new Date(), updated_at: new Date() },
# 5 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/blueskylodge/3.jpeg", restaurant_id: "5", created_at: new Date(), updated_at: new Date() },
# 5 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/blueskylodge/4.jpeg", restaurant_id: "5", created_at: new Date(), updated_at: new Date() },
# 5 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/blueskylodge/5.jpeg", restaurant_id: "5", created_at: new Date(), updated_at: new Date() },
# 5 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/blueskylodge/6.jpeg", restaurant_id: "5", created_at: new Date(), updated_at: new Date() },
# 6 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/blueskylodge/7.jpeg", restaurant_id: "6", created_at: new Date(), updated_at: new Date() },
# 6 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/bigsurriverinn/1.jpeg", restaurant_id: "6", created_at: new Date(), updated_at: new Date() },
# 6 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/bigsurriverinn/2.jpeg", restaurant_id: "6", created_at: new Date(), updated_at: new Date() },
# 6 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/bigsurriverinn/3.jpeg", restaurant_id: "6", created_at: new Date(), updated_at: new Date() },

# Pierre
# 7 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.78sZKhhTjSnFtNHty_v35AHaE6%26pid%3DApi&f=1", restaurant_id: "7", created_at: new Date(), updated_at: new Date() },
# 7 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.IjNGVcWHOOSOfnd8wT_qVgHaE8%26pid%3DApi&f=1", restaurant_id: "7", created_at: new Date(), updated_at: new Date() },
# 7 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.i4yzmBcjOHJR0jdmk4GuaAHaFj%26pid%3DApi&f=1", restaurant_id: "7", created_at: new Date(), updated_at: new Date() },
# 7 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.FY8tBbIbaA0mJs_ZmKc-0wHaD4%26pid%3DApi&f=1", restaurant_id: "7", created_at: new Date(), updated_at: new Date() },
# 8 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.w337j1OMkrySnmevWyTOLwAAAA%26pid%3DApi&f=1", restaurant_id: "8", created_at: new Date(), updated_at: new Date() },
# 8 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.yDsYhmhXez9Msi3HKbWZEwHaFj%26pid%3DApi&f=1", restaurant_id: "8", created_at: new Date(), updated_at: new Date() },
# 8 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.Zx98n9_BLsAglr0bPddQAgHaJ4%26pid%3DApi&f=1", restaurant_id: "8", created_at: new Date(), updated_at: new Date() },
# 8 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.l_S1DDzelEHHBO_YU0V98QAAAA%26pid%3DApi&f=1", restaurant_id: "8", created_at: new Date(), updated_at: new Date() },
# 9 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.tv5MUx9roSFgDF1U1E6pZwHaFj%26pid%3DApi&f=1", restaurant_id: "9", created_at: new Date(), updated_at: new Date() },
# 9 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.NOKdY3_1CpQp3AbVw6Mm7gHaD5%26pid%3DApi&f=1", restaurant_id: "9", created_at: new Date(), updated_at: new Date() },
# 9 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.G2XmIRmn2ZLO5aDaNrH97AHaFj%26pid%3DApi&f=1", restaurant_id: "9", created_at: new Date(), updated_at: new Date() },
# 9 { img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.OEaogVdr2N_isMwtAy0dzgHaE7%26pid%3DApi&f=1", restaurant_id: "9", created_at: new Date(), updated_at: new Date() },

# Jonathan
# 10 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/vagabondshouse/6.jpeg", restaurant_id: "10", created_at: new Date(), updated_at: new Date() },
# 10 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/vagabondshouse/7.jpeg", restaurant_id: "10", created_at: new Date(), updated_at: new Date() },
# 10 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/forestlodge/1.jpeg", restaurant_id: "10", created_at: new Date(), updated_at: new Date() },
# 10 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/forestlodge/2.jpeg", restaurant_id: "10", created_at: new Date(), updated_at: new Date() },
# 11 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/forestlodge/3.jpeg", restaurant_id: "11", created_at: new Date(), updated_at: new Date() },
# 11 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/forestlodge/4.jpeg", restaurant_id: "11", created_at: new Date(), updated_at: new Date() },
# 11 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/forestlodge/5.jpeg", restaurant_id: "11", created_at: new Date(), updated_at: new Date() },
# 11 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/forestlodge/6.jpeg", restaurant_id: "11", created_at: new Date(), updated_at: new Date() },
# 12 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/forestlodge/7.jpeg", restaurant_id: "12", created_at: new Date(), updated_at: new Date() },
# 12 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/thehideaway/1.jpeg", restaurant_id: "12", created_at: new Date(), updated_at: new Date() },
# 12 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/thehideaway/2.jpeg", restaurant_id: "12", created_at: new Date(), updated_at: new Date() },
# 12 { img_url: "https://stayquaint.s3.us-west-1.amazonaws.com/thehideaway/3.jpeg", restaurant_id: "12", created_at: new Date(), updated_at: new Date() },
